import type { Project, Category } from '@ig-types/index'

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    title: 'AI Attendance System',
    description:
      'A smart attendance management system powered by facial recognition using OpenCV and deep learning. It automatically marks attendance by detecting and identifying student faces in real time. Ideal for classrooms and corporate environments seeking to eliminate manual roll calls.',
    price: 1499,
    domain: 'AI & ML',
    difficulty: 'beginner',
    type: 'admin',
    technologies: ['Python', 'OpenCV', 'TensorFlow', 'Flask', 'SQLite'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-10T08:30:00Z',
    views: 4320,
    downloads: 312,
    rating: 4.7,
    reviewCount: 38,
    isTrending: true,
    isNew: false,
    isFeatured: false,
    isTopSelling: false,
    tags: ['AI', 'Face Recognition', 'Attendance', 'Python', 'OpenCV'],
  },
  {
    id: 'proj-002',
    title: 'E-Commerce Platform',
    description:
      'A fully functional e-commerce web application with product listings, cart management, secure payment gateway integration, and an admin dashboard. Built with the MERN stack, it supports JWT authentication, order tracking, and inventory management. Suitable for B2C retail businesses of any scale.',
    price: 2499,
    domain: 'Web Development',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['React', 'Node.js', 'MongoDB', 'Express', 'Stripe'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z',
    views: 3870,
    downloads: 428,
    rating: 4.8,
    reviewCount: 47,
    isTrending: false,
    isNew: false,
    isFeatured: false,
    isTopSelling: true,
    tags: ['MERN', 'E-Commerce', 'React', 'Node.js', 'Payment Gateway'],
  },
  {
    id: 'proj-003',
    title: 'Cybersecurity Toolkit',
    description:
      'A comprehensive offensive and defensive cybersecurity toolkit featuring network scanning, vulnerability assessment, password auditing, and log analysis modules. Built in Python with a clean CLI interface, it helps security researchers and ethical hackers perform penetration testing efficiently. Includes detailed documentation and sample reports.',
    price: 1999,
    domain: 'Cybersecurity',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Python', 'Nmap', 'Scapy', 'SQLite', 'Bash'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-02-05T11:00:00Z',
    updatedAt: '2026-03-15T09:45:00Z',
    views: 2150,
    downloads: 187,
    rating: 4.6,
    reviewCount: 22,
    isTrending: false,
    isNew: false,
    isFeatured: true,
    isTopSelling: false,
    tags: ['Cybersecurity', 'Pentesting', 'Python', 'Network Security', 'Ethical Hacking'],
  },
  {
    id: 'proj-004',
    title: 'ML Price Predictor',
    description:
      'A machine learning project that predicts real estate and stock prices using regression models and ensemble methods. It includes feature engineering pipelines, model comparison dashboards, and a Streamlit web interface for live predictions. Supports CSV uploads for custom dataset analysis.',
    price: 1299,
    domain: 'AI & ML',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['Python', 'Scikit-learn', 'Pandas', 'Streamlit', 'Matplotlib'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-20T14:00:00Z',
    views: 1980,
    downloads: 230,
    rating: 4.5,
    reviewCount: 29,
    isTrending: true,
    isNew: true,
    isFeatured: false,
    isTopSelling: false,
    tags: ['Machine Learning', 'Price Prediction', 'Streamlit', 'Python', 'Regression'],
  },
  {
    id: 'proj-005',
    title: 'Smart IoT Dashboard',
    description:
      'A real-time IoT monitoring dashboard that visualizes data from sensors such as temperature, humidity, and motion detectors. Built with Node.js and MQTT protocol, it pushes live updates to a React frontend via WebSockets. Perfect for smart home, agriculture, and industrial monitoring projects.',
    price: 999,
    domain: 'IoT',
    difficulty: 'beginner',
    type: 'admin',
    technologies: ['React', 'Node.js', 'MQTT', 'WebSocket', 'Chart.js'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-05-10T07:30:00Z',
    updatedAt: '2026-05-28T10:00:00Z',
    views: 1140,
    downloads: 98,
    rating: 4.3,
    reviewCount: 14,
    isTrending: false,
    isNew: true,
    isFeatured: false,
    isTopSelling: false,
    tags: ['IoT', 'Dashboard', 'MQTT', 'Real-Time', 'Sensors'],
  },
  {
    id: 'proj-006',
    title: 'Blockchain Voting System',
    description:
      'A decentralized voting platform built on Ethereum using Solidity smart contracts, ensuring tamper-proof and transparent elections. Voters authenticate with MetaMask wallets and cast ballots that are recorded immutably on-chain. Includes an admin panel for election setup and a public result explorer.',
    price: 3499,
    domain: 'Blockchain',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Solidity', 'React', 'Hardhat', 'ethers.js', 'MetaMask'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-02-18T13:00:00Z',
    updatedAt: '2026-04-05T11:20:00Z',
    views: 2890,
    downloads: 341,
    rating: 4.9,
    reviewCount: 41,
    isTrending: false,
    isNew: false,
    isFeatured: false,
    isTopSelling: true,
    tags: ['Blockchain', 'Ethereum', 'Smart Contract', 'Voting', 'Web3'],
  },
  {
    id: 'proj-007',
    title: 'Mobile Fitness App',
    description:
      'A cross-platform mobile fitness application that tracks workouts, calories, and health metrics with personalized goal-setting features. Built with React Native and integrated with a RESTful Node.js backend, it includes push notifications, progress charts, and social sharing. Supports both iOS and Android.',
    price: 1799,
    domain: 'Mobile Apps',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['React Native', 'Node.js', 'MongoDB', 'Firebase', 'Expo'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-05T09:15:00Z',
    updatedAt: '2026-04-22T16:00:00Z',
    views: 2470,
    downloads: 279,
    rating: 4.6,
    reviewCount: 33,
    isTrending: false,
    isNew: false,
    isFeatured: true,
    isTopSelling: false,
    tags: ['Mobile', 'Fitness', 'React Native', 'Cross-Platform', 'Health'],
  },
  {
    id: 'proj-008',
    title: 'Data Analytics Tool',
    description:
      'An interactive data analytics platform that allows users to upload datasets, perform exploratory analysis, and generate automated insights and visualizations. Built with Python and Dash, it supports statistical summaries, correlation heatmaps, and custom SQL queries. Designed for data science students and analysts.',
    price: 2199,
    domain: 'Data Science',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['Python', 'Dash', 'Pandas', 'Plotly', 'PostgreSQL'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-20T10:45:00Z',
    updatedAt: '2026-05-10T08:00:00Z',
    views: 1760,
    downloads: 164,
    rating: 4.4,
    reviewCount: 19,
    isTrending: false,
    isNew: false,
    isFeatured: false,
    isTopSelling: false,
    tags: ['Data Science', 'Analytics', 'Visualization', 'Python', 'Dash'],
  },
  {
    id: 'proj-009',
    title: 'Research Citation Manager',
    description:
      'A web-based citation and reference management tool that helps students and researchers organize their bibliography, import references from DOI or arXiv, and export in APA, MLA, or IEEE formats. Built with Vue.js and a lightweight Express backend, it also supports collaborative libraries. Great for thesis and journal paper writing.',
    price: 899,
    domain: 'Research Tools',
    difficulty: 'beginner',
    type: 'admin',
    technologies: ['Vue.js', 'Express', 'MongoDB', 'CrossRef API', 'PDF.js'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-05-20T06:00:00Z',
    updatedAt: '2026-06-01T09:30:00Z',
    views: 870,
    downloads: 73,
    rating: 4.2,
    reviewCount: 11,
    isTrending: false,
    isNew: true,
    isFeatured: false,
    isTopSelling: false,
    tags: ['Research', 'Citation', 'Bibliography', 'Vue.js', 'Academic'],
  },
  {
    id: 'proj-010',
    title: 'AI Resume Analyzer',
    description: 'An intelligent resume parsing and scoring platform that uses NLP to extract skills, experience, and education from uploaded resumes. Provides actionable feedback and ATS compatibility scores.',
    price: 1599,
    domain: 'AI & ML',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['Python', 'spaCy', 'Flask', 'React', 'PostgreSQL'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
    views: 3200,
    downloads: 275,
    rating: 4.7,
    reviewCount: 34,
    isTrending: true,
    isNew: false,
    isFeatured: true,
    isTopSelling: false,
    tags: ['AI', 'NLP', 'Resume', 'Python', 'Career'],
  },
  {
    id: 'proj-011',
    title: 'Smart Attendance System',
    description: 'A QR-code and geolocation-based attendance system for classrooms and offices. Teachers generate time-limited QR codes; students scan to mark attendance with location verification.',
    price: 1199,
    domain: 'Web Development',
    difficulty: 'beginner',
    type: 'admin',
    technologies: ['React', 'Node.js', 'MongoDB', 'QR.js', 'Google Maps API'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-04-20T11:00:00Z',
    views: 2800,
    downloads: 310,
    rating: 4.5,
    reviewCount: 28,
    isTrending: true,
    isNew: false,
    isFeatured: true,
    isTopSelling: false,
    tags: ['Attendance', 'QR Code', 'React', 'Geolocation', 'Education'],
  },
  {
    id: 'proj-012',
    title: 'Data Science Dashboard',
    description: 'An interactive analytics dashboard with drag-and-drop widgets, real-time data visualization, and automated report generation. Connects to SQL databases and CSV files.',
    price: 2299,
    domain: 'Data Science',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Python', 'Dash', 'Plotly', 'PostgreSQL', 'Redis'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
    views: 2450,
    downloads: 198,
    rating: 4.8,
    reviewCount: 25,
    isTrending: false,
    isNew: false,
    isFeatured: true,
    isTopSelling: true,
    tags: ['Data Science', 'Dashboard', 'Analytics', 'Visualization', 'Python'],
  },
  {
    id: 'proj-013',
    title: 'Inventory Management System',
    description: 'A complete inventory and warehouse management system with barcode scanning, stock alerts, supplier management, and purchase order generation. Features role-based access control.',
    price: 1899,
    domain: 'Web Development',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['React', 'Express', 'MySQL', 'Chart.js', 'JWT'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-01-25T07:00:00Z',
    updatedAt: '2026-03-10T12:00:00Z',
    views: 3100,
    downloads: 342,
    rating: 4.6,
    reviewCount: 39,
    isTrending: true,
    isNew: false,
    isFeatured: false,
    isTopSelling: true,
    tags: ['Inventory', 'Management', 'ERP', 'React', 'MySQL'],
  },
  {
    id: 'proj-014',
    title: 'College ERP System',
    description: 'A comprehensive Enterprise Resource Planning system for colleges covering student enrollment, fee management, exam scheduling, result publishing, and faculty management modules.',
    price: 3999,
    domain: 'Web Development',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Angular', 'Spring Boot', 'PostgreSQL', 'Redis', 'Docker'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-04-15T09:00:00Z',
    views: 4100,
    downloads: 456,
    rating: 4.9,
    reviewCount: 52,
    isTrending: true,
    isNew: false,
    isFeatured: true,
    isTopSelling: true,
    tags: ['ERP', 'College', 'Management', 'Angular', 'Spring Boot'],
  },
  {
    id: 'proj-015',
    title: 'Food Delivery App',
    description: 'A complete food delivery platform with customer app, restaurant dashboard, and delivery partner tracking. Features real-time order tracking, payment integration, and rating system.',
    price: 2799,
    domain: 'Mobile Apps',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['React Native', 'Node.js', 'MongoDB', 'Socket.io', 'Stripe'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-20T08:00:00Z',
    updatedAt: '2026-05-01T14:00:00Z',
    views: 3650,
    downloads: 389,
    rating: 4.7,
    reviewCount: 44,
    isTrending: false,
    isNew: false,
    isFeatured: true,
    isTopSelling: true,
    tags: ['Food Delivery', 'Mobile', 'React Native', 'Real-Time', 'E-Commerce'],
  },
  {
    id: 'proj-016',
    title: 'AI Chatbot Platform',
    description: 'A customizable AI chatbot builder with drag-and-drop flow editor, NLP intent recognition, multi-channel deployment (web, WhatsApp, Telegram), and analytics dashboard.',
    price: 2499,
    domain: 'AI & ML',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Python', 'FastAPI', 'React', 'OpenAI API', 'WebSocket'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-05-25T11:00:00Z',
    views: 5200,
    downloads: 412,
    rating: 4.8,
    reviewCount: 48,
    isTrending: true,
    isNew: true,
    isFeatured: true,
    isTopSelling: false,
    tags: ['AI', 'Chatbot', 'NLP', 'Python', 'OpenAI'],
  },
  {
    id: 'proj-017',
    title: 'Blockchain Voting System',
    description: 'A secure decentralized voting platform using Ethereum smart contracts with voter verification, real-time result tallying, and complete audit trail on the blockchain.',
    price: 3299,
    domain: 'Blockchain',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Solidity', 'React', 'Hardhat', 'ethers.js', 'IPFS'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-04-20T08:00:00Z',
    views: 2900,
    downloads: 267,
    rating: 4.6,
    reviewCount: 31,
    isTrending: true,
    isNew: false,
    isFeatured: false,
    isTopSelling: false,
    tags: ['Blockchain', 'Voting', 'Ethereum', 'Smart Contract', 'Web3'],
  },
  {
    id: 'proj-018',
    title: 'Hospital Management System',
    description: 'A comprehensive HMS with patient registration, appointment scheduling, electronic health records, billing, pharmacy management, and lab report integration.',
    price: 3599,
    domain: 'Web Development',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['React', 'Django', 'PostgreSQL', 'Celery', 'Docker'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
    views: 3800,
    downloads: 378,
    rating: 4.7,
    reviewCount: 42,
    isTrending: false,
    isNew: false,
    isFeatured: true,
    isTopSelling: true,
    tags: ['Hospital', 'Management', 'Healthcare', 'Django', 'EHR'],
  },
  {
    id: 'proj-019',
    title: 'ML Price Predictor Pro',
    description: 'An advanced price prediction engine using ensemble ML models (XGBoost, Random Forest, LSTM) for real estate, stocks, and cryptocurrency with backtesting capabilities.',
    price: 1799,
    domain: 'AI & ML',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['Python', 'XGBoost', 'TensorFlow', 'Streamlit', 'yfinance'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-05-05T07:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
    views: 2100,
    downloads: 189,
    rating: 4.5,
    reviewCount: 21,
    isTrending: true,
    isNew: true,
    isFeatured: false,
    isTopSelling: false,
    tags: ['ML', 'Price Prediction', 'XGBoost', 'LSTM', 'Finance'],
  },
  {
    id: 'proj-020',
    title: 'Cloud Storage Platform',
    description: 'A Dropbox-like cloud storage solution with file upload/download, folder management, file sharing links, version history, and real-time collaboration features.',
    price: 2199,
    domain: 'Cloud Computing',
    difficulty: 'intermediate',
    type: 'admin',
    technologies: ['Next.js', 'AWS S3', 'Node.js', 'PostgreSQL', 'WebSocket'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-05-30T12:00:00Z',
    views: 1850,
    downloads: 156,
    rating: 4.4,
    reviewCount: 18,
    isTrending: false,
    isNew: true,
    isFeatured: true,
    isTopSelling: false,
    tags: ['Cloud', 'Storage', 'AWS', 'Next.js', 'File Sharing'],
  },
  {
    id: 'proj-021',
    title: 'Cybersecurity Scanner',
    description: 'An automated web application security scanner that detects XSS, SQL injection, CSRF, and other OWASP Top 10 vulnerabilities with detailed PDF reports.',
    price: 2399,
    domain: 'Cybersecurity',
    difficulty: 'advanced',
    type: 'admin',
    technologies: ['Python', 'Selenium', 'BeautifulSoup', 'SQLMap', 'Flask'],
    screenshots: [],
    status: 'published',
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-05-05T11:00:00Z',
    views: 2600,
    downloads: 234,
    rating: 4.6,
    reviewCount: 27,
    isTrending: true,
    isNew: false,
    isFeatured: false,
    isTopSelling: false,
    tags: ['Cybersecurity', 'Scanner', 'OWASP', 'Pentesting', 'Python'],
  },
]

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    name: 'AI & ML',
    slug: 'ai-ml',
    icon: 'Brain',
    count: 24,
    color: '#6366f1',
    description: 'Artificial intelligence and machine learning projects using Python, TensorFlow, and more.',
  },
  {
    id: 'cat-02',
    name: 'Web Development',
    slug: 'web-development',
    icon: 'Globe',
    count: 31,
    color: '#3b82f6',
    description: 'Full-stack web applications built with modern frameworks like React, Next.js, and Node.js.',
  },
  {
    id: 'cat-03',
    name: 'Cybersecurity',
    slug: 'cybersecurity',
    icon: 'Shield',
    count: 14,
    color: '#ef4444',
    description: 'Ethical hacking tools, network security scanners, and vulnerability assessment projects.',
  },
  {
    id: 'cat-04',
    name: 'IoT',
    slug: 'iot',
    icon: 'Cpu',
    count: 18,
    color: '#10b981',
    description: 'Internet of Things projects featuring sensor integration, dashboards, and automation.',
  },
  {
    id: 'cat-05',
    name: 'Blockchain',
    slug: 'blockchain',
    icon: 'Link',
    count: 9,
    color: '#f59e0b',
    description: 'Decentralized applications, smart contracts, and Web3 projects on Ethereum and more.',
  },
  {
    id: 'cat-06',
    name: 'Mobile Apps',
    slug: 'mobile-apps',
    icon: 'Smartphone',
    count: 22,
    color: '#8b5cf6',
    description: 'Cross-platform and native mobile applications for iOS and Android using React Native and Flutter.',
  },
  {
    id: 'cat-07',
    name: 'Data Science',
    slug: 'data-science',
    icon: 'BarChart2',
    count: 17,
    color: '#06b6d4',
    description: 'Data analysis, visualization, and predictive modelling projects using Python and R.',
  },
  {
    id: 'cat-08',
    name: 'Cloud Computing',
    slug: 'cloud-computing',
    icon: 'Cloud',
    count: 11,
    color: '#64748b',
    description: 'Cloud-native applications and DevOps pipelines on AWS, GCP, and Azure.',
  },
  {
    id: 'cat-09',
    name: 'Research Tools',
    slug: 'research-tools',
    icon: 'BookOpen',
    count: 8,
    color: '#ec4899',
    description: 'Productivity tools for academic research, citation management, and literature review.',
  },
  {
    id: 'cat-10',
    name: 'Game Development',
    slug: 'game-development',
    icon: 'Gamepad2',
    count: 13,
    color: '#f97316',
    description: '2D and 3D game projects built with Unity, Godot, and browser-based frameworks.',
  },
]

export const TESTIMONIALS = [
  {
    id: 'test-01',
    name: 'Rahul S.',
    role: 'B.Tech CSE Final Year',
    college: 'IIT Bombay',
    rating: 5,
    text: 'InnovateGuide saved my final year project submission. The AI Attendance System was well-documented and ran perfectly out of the box. My guide was impressed with the code quality and architecture.',
    avatar: 'RS',
  },
  {
    id: 'test-02',
    name: 'Priya M.',
    role: 'MCA Student',
    college: 'NIT Trichy',
    rating: 5,
    text: 'I ordered a custom project for my thesis and the team delivered exactly what I needed within the timeline. The WhatsApp support was incredibly responsive. Highly recommended for serious students.',
    avatar: 'PM',
  },
  {
    id: 'test-03',
    name: 'Arjun K.',
    role: 'BE Electronics',
    college: 'BITS Pilani',
    rating: 4,
    text: 'The Smart IoT Dashboard project was perfect for my mini project. Clean code, great comments, and a working demo video made it easy to understand and present. Worth every rupee.',
    avatar: 'AK',
  },
]

export const FAQ_ITEMS = [
  {
    id: 'faq-01',
    question: 'What do I get after purchasing a project?',
    answer:
      'After purchase, you receive the complete source code, a detailed README with setup instructions, a project report template, and access to WhatsApp support for any queries. All files are delivered via a secure download link within minutes.',
  },
  {
    id: 'faq-02',
    question: 'Are the projects suitable for academic submission?',
    answer:
      'Yes. All projects include documentation aligned with standard academic formats. However, we recommend using the projects as learning references and adding your own modifications to ensure originality before submission.',
  },
  {
    id: 'faq-03',
    question: 'Can I request a custom project?',
    answer:
      'Absolutely. Use the Custom Project Request form to describe your requirements, budget, and deadline. Our team will review your request and get back to you on WhatsApp within 24 hours with a quote and timeline.',
  },
  {
    id: 'faq-04',
    question: 'What technologies are the projects built with?',
    answer:
      'Our catalogue covers a wide range of stacks including Python, MERN, React Native, Flutter, Solidity, Java, and more. Each project listing clearly mentions the technologies used so you can choose based on your coursework.',
  },
  {
    id: 'faq-05',
    question: 'Is there any support after purchase?',
    answer:
      'Yes, all purchases include 7 days of post-sale WhatsApp support for setup and configuration issues. For custom projects, support extends through the agreed delivery period and one week after final delivery.',
  },
  {
    id: 'faq-06',
    question: 'How are payments processed?',
    answer:
      'Payments are handled securely via Razorpay, supporting UPI, debit/credit cards, and net banking. We do not store any payment details on our servers. All transactions are encrypted and PCI-DSS compliant.',
  },
]

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Browse & Choose',
    description:
      'Explore our catalogue of 150+ student and professional projects across 10 domains. Filter by technology, difficulty, or budget to find the perfect match for your requirements.',
    icon: 'Search',
  },
  {
    step: 2,
    title: 'Purchase Securely',
    description:
      'Add your chosen project to cart and complete payment via Razorpay using UPI, card, or net banking. Your download link is generated instantly after payment confirmation.',
    icon: 'ShoppingCart',
  },
  {
    step: 3,
    title: 'Download & Build',
    description:
      'Receive the complete source code, documentation, and setup guide. Our WhatsApp support team is available to help you run and customise the project within 7 days of purchase.',
    icon: 'Download',
  },
]
